/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package numericui;

import java.util.HashSet;
import java.util.Set;
import numeric.*;

/**
 *
 * @author Caleb Willson
 */
public class NumericUI extends javax.swing.JFrame {

    /**
     * Creates new form NumericUI
     */
    public NumericUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gcdDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        gcdX = new javax.swing.JTextField();
        gcdY = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        gcdOut = new javax.swing.JTextArea();
        gcdExit = new javax.swing.JButton();
        gcdComp = new javax.swing.JButton();
        facDialog = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        facX = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        facOut = new javax.swing.JTextArea();
        facExit = new javax.swing.JButton();
        facComp = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuGCD = new javax.swing.JMenuItem();
        menuFac = new javax.swing.JMenuItem();

        gcdDialog.setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GCD Calculator");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        gcdX.setToolTipText("Input 1");
        gcdX.setMinimumSize(new java.awt.Dimension(80, 22));

        gcdY.setToolTipText("Input 2");
        gcdY.setMinimumSize(new java.awt.Dimension(80, 22));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        gcdOut.setEditable(false);
        gcdOut.setColumns(20);
        gcdOut.setRows(5);
        jScrollPane1.setViewportView(gcdOut);

        gcdExit.setText("Exit");
        gcdExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gcdExitActionPerformed(evt);
            }
        });

        gcdComp.setText("Compute");
        gcdComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gcdCompActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gcdDialogLayout = new javax.swing.GroupLayout(gcdDialog.getContentPane());
        gcdDialog.getContentPane().setLayout(gcdDialogLayout);
        gcdDialogLayout.setHorizontalGroup(
            gcdDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gcdDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gcdDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(gcdDialogLayout.createSequentialGroup()
                        .addComponent(gcdX, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gcdY, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gcdDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(gcdComp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gcdExit)))
                .addContainerGap())
        );

        gcdDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {gcdComp, gcdExit});

        gcdDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {gcdX, gcdY});

        gcdDialogLayout.setVerticalGroup(
            gcdDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gcdDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gcdDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gcdX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gcdY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gcdDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gcdExit)
                    .addComponent(gcdComp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        facDialog.setResizable(false);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Factorial Calculator");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        facX.setToolTipText("Input");
        facX.setMinimumSize(new java.awt.Dimension(80, 22));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        facOut.setEditable(false);
        facOut.setColumns(20);
        facOut.setRows(5);
        jScrollPane2.setViewportView(facOut);

        facExit.setText("Exit");
        facExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facExitActionPerformed(evt);
            }
        });

        facComp.setText("Compute");
        facComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facCompActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout facDialogLayout = new javax.swing.GroupLayout(facDialog.getContentPane());
        facDialog.getContentPane().setLayout(facDialogLayout);
        facDialogLayout.setHorizontalGroup(
            facDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(facComp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(facExit))
                    .addGroup(facDialogLayout.createSequentialGroup()
                        .addComponent(facX, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        facDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {facComp, facExit});

        facDialogLayout.setVerticalGroup(
            facDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(facX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(facDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facExit)
                    .addComponent(facComp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Compute");

        menuGCD.setText("GCD");
        menuGCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openGCD(evt);
            }
        });
        jMenu2.add(menuGCD);

        menuFac.setText("Factorial");
        menuFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFactorial(evt);
            }
        });
        jMenu2.add(menuFac);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menuExitActionPerformed

    private void openGCD(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openGCD
        // TODO add your handling code here:
        gcdDialog.setModal(true);
        gcdDialog.pack();
        gcdDialog.setVisible(true);
    }//GEN-LAST:event_openGCD

    private void openFactorial(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFactorial
        // TODO add your handling code here:
        facDialog.setModal(true);
        facDialog.pack();
        facDialog.setVisible(true);
    }//GEN-LAST:event_openFactorial

    private void facExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facExitActionPerformed
        // Close the factorial dialog box
        facDialog.dispose();
    }//GEN-LAST:event_facExitActionPerformed
    
    private void gcdExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gcdExitActionPerformed
        // Close the GCD dialog box
        gcdDialog.dispose();
    }//GEN-LAST:event_gcdExitActionPerformed
    
    /**
     * 
     * @param evt 
     */
    private void gcdCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gcdCompActionPerformed
        // TODO add your handling code here:
        int x = 0;
        int y = 0;
        
        try {
            x = Integer.parseInt(gcdX.getText());
        }
        catch (NumberFormatException e) {
            gcdOut.setText("Please enter an integer value.");
            return;
        }
        
        try {
            y = Integer.parseInt(gcdY.getText());
        }
        catch (NumberFormatException e) {
            gcdOut.setText("Please enter an integer value.");
            return;
        }
        
        int result = GCD.compute(x,y);
        gcdOut.setText("The GCD of " + x + " and " + y + " is " + result + ".");
    }//GEN-LAST:event_gcdCompActionPerformed
    
    /**
     * 
     * @param evt 
     */
    private void facCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facCompActionPerformed
        // TODO add your handling code here:
        int x = 0;
        
        try {
            x = Integer.parseInt(facX.getText());
        }
        catch (NumberFormatException e) {
            facOut.setText("Please enter an integer value.");
            return;
        }
        
        try {
            double result = Factorial.compute(x);
            facOut.setText("The factorial of " + x + " is " + result + ".");
        }
        catch (NegativeFactorialException e) {
            facOut.setText("Please enter a positive integer.");
        }
    }//GEN-LAST:event_facCompActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumericUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumericUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumericUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumericUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumericUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton facComp;
    private javax.swing.JDialog facDialog;
    private javax.swing.JButton facExit;
    private javax.swing.JTextArea facOut;
    private javax.swing.JTextField facX;
    private javax.swing.JButton gcdComp;
    private javax.swing.JDialog gcdDialog;
    private javax.swing.JButton gcdExit;
    private javax.swing.JTextArea gcdOut;
    private javax.swing.JTextField gcdX;
    private javax.swing.JTextField gcdY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuFac;
    private javax.swing.JMenuItem menuGCD;
    // End of variables declaration//GEN-END:variables
}
